<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dragon_Nutrex_Web</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Infrastructure\Data\consumo_diario.json" />
    <Content Remove="Infrastructure\Data\menus.json" />
    <Content Remove="Infrastructure\Data\menu_detalles.json" />
    <Content Remove="Infrastructure\Data\productos.json" />
    <Content Remove="Infrastructure\Data\usuarios.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Infrastructure\Data\consumo_diario.json" />
    <None Include="Infrastructure\Data\menus.json" />
    <None Include="Infrastructure\Data\menu_detalles.json" />
    <None Include="Infrastructure\Data\productos.json" />
    <None Include="Infrastructure\Data\usuarios.json" />
  </ItemGroup>

</Project>
